name: Deployment
on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    name: Test Job
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Print Test Environment MongoDB UserName 
        run: |
          echo "${{ vars.MONGODB_USERNAME }}"



  deploy:
    name: Deploy Job
    environment: staging
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Print Staging Environment MongoDB UserName
        run: |        
          echo "${{ vars.MONGODB_USERNAME}}"
