name: Deployment
on:
  push:
    branches:
      - main
      - dev

env:
  MONGODB_DB_NAME: sample_mflix

jobs:

  test:
    environment: test
    env: 
      MONGODB_CLUSTER_ADDRESS: test.wnzd5ah.mongodb.net

      PORT: 8080

    runs-on: ubuntu-latest
    steps:
      
      - name: Output information
        run: |
          echo "${{ env.MONGODB_USERNAME }}"



  deploy:
    environment: staging
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo {{ env.MONGODB_USERNAME}}
